version: "3"
services:
    nginx:
        image: nginx:1.15.7-alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
            - ./html:/var/www/html:cached
        depends_on:
            - php
    php:
        build: ./php
        ports:
            - "9000"
        volumes:
            - ./html:/var/www/html:cached
            - ./php/php.ini:/usr/local/etc/php/php.ini:cached
            - ./log:/var/log:cached
    pgsql:
        build:
            context: .
            dockerfile: ./pgsql/Dockerfile
            args:
                - DB_LANG=ja_JP
        container_name: pgsql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: develop_db
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        restart: always
        volumes:
            - ./pgadmin:/var/lib/pgadmin
volumes:
    db: {}
